steps:
  # Bước 1: Tải tệp credentials từ Secret Manager
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Lấy secret từ Secret Manager và lưu vào tệp
        gcloud secrets versions access latest --secret="google-credentials" > /workspace/google-credentials.json
        gcloud auth activate-service-account --key-file=/workspace/google-credentials.json
        gcloud config set project ${_PROJECT_ID}

  # Bước 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-northeast1-docker.pkg.dev/calcium-post-400103/hello-world-service/web@sha256:40304e159419980446801a1e94d7afed0e2c90fb3d4f94c4a5ff29ca03a61f77',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-northeast1-docker.pkg.dev/calcium-post-400103/hello-world-service/web:latest'
    ]


serviceAccount: "projects/${_PROJECT_ID}/serviceAccounts/cloud-build-sa@${_PROJECT_ID}.iam.gserviceaccount.com"

# Substitutions
substitutions:
  _PROJECT_ID: "calcium-post-400103"
  _APP_NAME: "hello-world-service"
  _LOCATION: "asia-northeast1"
  _WEB_IMAGE_URL: "asia-northeast1-docker.pkg.dev/calcium-post-400103/hello-world-service/web:latest"


# Timeout cho build (tối đa 10 phút)
options:
  logging: CLOUD_LOGGING_ONLY
timeout: "600s"

