steps:
  # Bước 1: Tải tệp credentials từ Secret Manager
  - name: gcr.io/cloud-builders/gcloud
    args:
      - bash
      - -c
      - |
        # Lấy secret chứa credentials từ Secret Manager
        gcloud secrets versions access latest --secret="google-credentials" > /workspace/google-credentials.json
        gcloud auth activate-service-account --key-file=/workspace/google-credentials.json
        gcloud config set project ${_PROJECT_ID}

  # 2. Build Docker Image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--platform=linux/amd64",
        "-t",
        "${_WEB_IMAGE_URL}",
        "."
      ]

  # 3. Push Docker Image lên Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_WEB_IMAGE_URL}"
      ]

  # 4. Deploy lên Cloud Run bằng Terraform
  - name: hashicorp/terraform:light
    entrypoint: bash
    args:
      - -c
      - |
        cd terraform
        terraform init
        terraform apply -var="project_id=$_PROJECT_ID" -var="location=$_LOCATION" -var="name=$_APP_NAME" -auto-approve

serviceAccount: "projects/${_PROJECT_ID}/serviceAccounts/cloud-build-sa@${_PROJECT_ID}.iam.gserviceaccount.com"

# Substitutions
substitutions:
  _PROJECT_ID: ""
  _APP_NAME: ""
  _LOCATION: ""
  _WEB_IMAGE_URL: ""

# Timeout cho build (tối đa 10 phút)
options:
  logging: CLOUD_LOGGING_ONLY
timeout: "600s"

